### ISSUE TITLE
error if sent (test) message from Grafana v10.2.2

### ISSUE THREAD

**Issue by hvdort** [schlauerlauer/alertmanager-webhook-signal#5]
Is this incompatible with Grafana v10.2.2 or latest version of https://github.com/bbernhard/signal-cli-rest-api?

If I use the bundeled grafana.json with curl, it works, but using Grafana Contact point (webhook), I receive an success in Grafana but an error 400 coming from signal-cli-rest-api.

This is the JSON from Grafana what I have captured:

{
"receiver":"",
"status":"firing",
"alerts":[{
	"status":"firing",
	"labels":{"alertname":"TestAlert","instance":"Grafana"},
	"annotations":{"summary":"Notification test"},
	"startsAt":"2023-12-04T13:12:07.92607674+01:00",
	"endsAt":"0001-01-01T00:00:00Z",
	"generatorURL":"",
	"fingerprint":"57c6d9296de2ad39",
	"silenceURL":"https://grafanaxxxxxxx.xxxx.xxxxx/alerting/silence/new?alertmanager=grafana\u0026matcher=alertname%3DTestAlert\u0026matcher=instance%3DGrafana",
	"dashboardURL":"",
	"panelURL":"",
	"values":null,
	"valueString":"[ metric='foo' labels={instance=bar} value=10 ]"}],
"groupLabels":{},
"commonLabels":{"alertname":"TestAlert","instance":"Grafana"},"commonAnnotations":{"summary":"Notification test"},
"externalURL":"https://grafanaxxxxxxx.xxxx.xxxxx/","version":"1",
"groupKey":"{alertname=\"TestAlert\",
instance=\"Grafana\"}2023-12-04 13:12:07.92607674 +0100 CET m=+448423.180184511",
"truncatedAlerts":0,
"orgId":1,
"title":"[FIRING:1]  (TestAlert Grafana)",
"state":"alerting",
"message":"**Firing**\n\nValue: [no value]\nLabels:\n - alertname = TestAlert\n - instance = Grafana\nAnnotations:\n - summary = Notification test\nSilence: https://grafanaxxxxxxx.xxxx.xxxxx/alerting/silence/new?alertmanager=grafana\u0026matcher=alertname%3DTestAlert\u0026matcher=instance%3DGrafana\n"
}

**Comment by schlauerlauer** [comment]
Hi, thanks for the issue!

This should be fixed now. Could you try again please?
