### ISSUE TITLE
Add emoji according to the status of the alert

### ISSUE THREAD

**Issue by dabizidabi** [schlauerlauer/alertmanager-webhook-signal#9]
Hello, is it possible to add an emoji at the beginning of the message according to the status of the alert? For example, if the status is firing, add :exclamation: at the beginning of the message, and if it is resolved - add :white_check_mark:

![image](https://github.com/schlauerlauer/alertmanager-webhook-signal/assets/60040394/f6f275ff-7237-496d-97c0-9ecade35d0b4)

**Comment by schlauerlauer** [comment]
Hi, thanks for the suggestion!

I will add text templates to customize the alert message in the coming days.
This will allow you to put emojis in the message.

**Comment by dabizidabi** [comment]
Hi @schlauerlauer!
Any updates for these improvements?
